### ISSUE TITLE
Install manually fails

### ISSUE THREAD

**Issue by ckrey** [owntracks/frontend#26]
Trying to install on Debian 9.12. Are any dependencies missing?

Step 1:
```
$ yarn install
yarn install v1.22.0
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.9: The platform "linux" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.1.2: The platform "linux" is incompatible with this module.
info "fsevents@2.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > vue2-leaflet@2.5.2" has unmet peer dependency "@types/leaflet@^1.5.7".
warning " > babel-core@7.0.0-bridge.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "babel-jest > babel-preset-jest > @babel/plugin-syntax-object-rest-spread@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning " > @vue/eslint-config-prettier@6.0.0" has unmet peer dependency "prettier@>= 1.13.0".
warning " > babel-jest@25.1.0" has unmet peer dependency "@babel/core@^7.0.0".
warning "babel-jest > babel-preset-jest@25.1.0" has unmet peer dependency "@babel/core@^7.0.0".
warning "babel-jest > babel-preset-jest > @babel/plugin-syntax-bigint@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning " > eslint-plugin-prettier@3.1.2" has unmet peer dependency "prettier@>= 1.13.0".
warning " > moment-locales-webpack-plugin@1.1.2" has unmet peer dependency "webpack@^1 || ^2 || ^3 || ^4".
warning " > sass-loader@8.0.2" has unmet peer dependency "webpack@^4.36.0 || ^5.0.0".
[4/4] Building fresh packages...
Done in 34.41s.
```
Step 2:
```
$ yarn build
yarn run v1.22.0
$ vue-cli-service build
module.js:550
    throw err;
    ^

Error: Cannot find module 'vue-cli-plugin-i18n'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at idToPlugin (/home/ckrey/.config/yarn/global/node_modules/@vue/cli-service/lib/Service.js:149:14)
    at Object.keys.concat.filter.map.id (/home/ckrey/.config/yarn/global/node_modules/@vue/cli-service/lib/Service.js:188:20)
    at Array.map (<anonymous>)
    at Service.resolvePlugins (/home/ckrey/.config/yarn/global/node_modules/@vue/cli-service/lib/Service.js:174:10)
    at new Service (/home/ckrey/.config/yarn/global/node_modules/@vue/cli-service/lib/Service.js:33:25)
    at Object.<anonymous> (/home/ckrey/.config/yarn/global/node_modules/@vue/cli-service/bin/vue-cli-service.js:15:17)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by linusg** [comment]
Hi @ckrey,

this is weird. I don't see an obvious cause right now. A few thoughts:

- The command mentioned in the README (`yarn install --production`) does not actually install all required dependencies, I'll have to update that. Seems like you didn't use that flag though.
- Can you please check a couple of things?

  - Has `vue-cli-plugin-i18n` actually been installed? `ls -la node_modules/vue-cli-plugin-i18n/` should tell.
  - Can you `rm -rf node_modules && yarn install && yarn build` again? Maybe it was a weird one-time-issue that now resolved itself.
  - If that fails again, can you please run `yarn install --verbose` and post the (huge) log output somewhere (pastebin etc)?

**Comment by ckrey** [comment]
* no, `vue-cli-plugin-i18n` has not been installed

* after `rm -rf node_modules`
```
$ yarn install
yarn install v1.22.0
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.9: The platform "linux" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.1.2: The platform "linux" is incompatible with this module.
info "fsevents@2.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > vue2-leaflet@2.5.2" has unmet peer dependency "@types/leaflet@^1.5.7".
warning " > babel-core@7.0.0-bridge.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "babel-jest > babel-preset-jest > @babel/plugin-syntax-object-rest-spread@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning " > @vue/eslint-config-prettier@6.0.0" has unmet peer dependency "prettier@>= 1.13.0".
warning " > babel-jest@25.1.0" has unmet peer dependency "@babel/core@^7.0.0".
warning "babel-jest > babel-preset-jest@25.1.0" has unmet peer dependency "@babel/core@^7.0.0".
warning "babel-jest > babel-preset-jest > @babel/plugin-syntax-bigint@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning " > eslint-plugin-prettier@3.1.2" has unmet peer dependency "prettier@>= 1.13.0".
warning " > moment-locales-webpack-plugin@1.1.2" has unmet peer dependency "webpack@^1 || ^2 || ^3 || ^4".
warning " > sass-loader@8.0.2" has unmet peer dependency "webpack@^4.36.0 || ^5.0.0".
[4/4] Building fresh packages...
Done in 34.62s.
```
```
$ yarn build
yarn run v1.22.0
$ vue-cli-service build

⠙  Building for production... ERROR  WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration has an unknown property 'publicPath'. These properties are valid:
   object { amd?, bail?, cache?, context?, dependencies?, devServer?, devtool?, entry?, externals?, infrastructureLogging?, loader?, mode?, module?, name?, node?, optimization?, output?, parallelism?, performance?, plugins?, profile?, recordsInputPath?, recordsOutputPath?, recordsPath?, resolve?, resolveLoader?, serve?, stats?, target?, watch?, watchOptions? }
   For typos: please correct them.
   For loader options: webpack >= v2.0.0 no longer allows custom properties in configuration.
     Loaders should be updated to allow passing options via loader options in module.rules.
     Until loaders are updated one can use the LoaderOptionsPlugin to pass these options to the loader:
     plugins: [
       new webpack.LoaderOptionsPlugin({
         // test: /\.xxx$/, // may apply this only for some modules
         options: {
           publicPath: …
         }
       })
     ]
WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration has an unknown property 'publicPath'. These properties are valid:
   object { amd?, bail?, cache?, context?, dependencies?, devServer?, devtool?, entry?, externals?, infrastructureLogging?, loader?, mode?, module?, name?, node?, optimization?, output?, parallelism?, performance?, plugins?, profile?, recordsInputPath?, recordsOutputPath?, recordsPath?, resolve?, resolveLoader?, serve?, stats?, target?, watch?, watchOptions? }
   For typos: please correct them.
   For loader options: webpack >= v2.0.0 no longer allows custom properties in configuration.
     Loaders should be updated to allow passing options via loader options in module.rules.
     Until loaders are updated one can use the LoaderOptionsPlugin to pass these options to the loader:
     plugins: [
       new webpack.LoaderOptionsPlugin({
         // test: /\.xxx$/, // may apply this only for some modules
         options: {
           publicPath: …
         }
       })
     ]
    at webpack (/home/ckrey/frontend/node_modules/webpack/lib/webpack.js:31:9)
    at Promise (/home/ckrey/frontend/node_modules/@vue/cli-service/lib/commands/build/index.js:192:5)
    at new Promise (<anonymous>)
    at build (/home/ckrey/frontend/node_modules/@vue/cli-service/lib/commands/build/index.js:191:10)
    at <anonymous>
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by ckrey** [comment]
Sorry for the confusion, after `rm -rf node_modules && yarn install && yarn build` it worked! Maybe it was a weird one-time-issue that now resolved itself.

**Comment by linusg** [comment]
Glad it's working now! I was concerned for a second, as the same commands used inside the Docker container certainly should work outside of a containerised just fine...
